# Generated by Django 3.0.3 on 2020-02-18 01:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0003_auto_20200216_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 18, 1, 8, 37, 876519, tzinfo=utc)),
        ),
    ]
