# Generated by Django 3.0.3 on 2020-02-18 02:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0006_auto_20200218_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 18, 2, 20, 20, 7845, tzinfo=utc)),
        ),
    ]
