# Generated by Django 3.0.3 on 2020-02-24 01:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0010_auto_20200219_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 24, 1, 34, 57, 78452, tzinfo=utc)),
        ),
    ]
