# Generated by Django 3.0.3 on 2020-02-14 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200213_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
